In [4]:
from math import cos, sin, acos, atan, sqrt 
import numpy as np

In [5]:
a1 = a2 = len_unit = 0.4 * sqrt(2)
r2 = centre_mass = len_unit / 2
mass = len_unit * 1.9

coord_points = [(0.3, 0.3), (0.3, 0.4), (0.3, 0.5), (0.3, 0.6), 
                (0.3, 0.7), (0.3, 0.8), (0.4, 0.8), (0.5, 0.8), 
                (0.6, 0.8), (0.7, 0.8), (0.8, 0.8), (0.8, 0.7), 
                (0.8, 0.6), (0.8, 0.5), (0.8, 0.4), (0.8, 0.3)]
coord_unit, alpha, beta = [], [], []

In [7]:
for (x, y) in coord_points:  
    lengs = sqrt(x ** 2 + y ** 2)
    
    alpha.append(atan(x / y) - acos((x ** 2 + y ** 2) / (2 * len_unit * lengs)))   
    beta.append(acos((2 * len_unit ** 2 - x ** 2 - y ** 2) / (2 * len_unit ** 2)))
    
    coord_unit.append((sin(alpha[-1]) * len_unit, cos(alpha[-1]) * len_unit))

In [8]:
e, w, Jc2, M1, M2 = [], [(0, 0)], [], [], []

Jc1 = 0.5 * mass * len_unit ** 2

for i in range(1, len(alpha)):
    Jc2.append(0.5 * mass * (a1 ** 2) + mass * (a2 ** 2) + (0.5 * a2 ** 2) + 2 * 0.5 * (a1)**2 * cos(beta[i]))
    w.insert(i - 1, [abs(alpha[i] - alpha[i - 1]), abs(beta[i] - beta[i - 1])])
    e.insert(i - 1, [abs(w[i][0] - w[i - 1][0]), abs(w[i][1] - w[i - 1][1])])

0.17196836918456845 0.17196836918456845


In [23]:
d1, d2, d3 = [], [], []

for i in range(len(Jc2)):
    d1.append(0.5 * (Jc1 + mass * len_unit ** 2 + 2 * mass * len_unit * centre_mass * cos(beta[i]) + mass * centre_mass ** 2 + Jc2[i]))
    d2.append(0.5 * (mass * len_unit * centre_mass * cos(beta[i]) + mass * centre_mass ** 2 + Jc2[i]))
    d3.append(0.5 * mass * centre_mass ** 2 + 0.5 * Jc2[i])

In [63]:
M = []
for i in range(len(d1)-1):
    A = [[2 * d1[i], 2 * d2[i]],
         [2 * d2[i], 2 * d3[i]]]

    B = [[-2 * m * a1 * r2 * sin(beta[i]) * W[i][1], -m * a1 * r2 * sin(beta[i]) * W[i][1]],
         [m * a1 * r2 * sin(beta[i]) * W[i][0], 0]]

    M.append(np.array(A)@np.array(E[i]) + np.array(B).reshape(2,-1)@np.array(W[i]))

In [69]:
print("      M1          M2")
for i in range(len(M)):
    print(i, M[i])

      M1          M2
0 [0.10188639 0.07344148]
1 [0.0194642  0.02040712]
2 [0.0573441  0.04486753]
3 [0.05016288 0.04428971]
4 [0.18822226 0.15479022]
5 [0.02601854 0.03530789]
6 [0.03073059 0.0431274 ]
7 [0.05156113 0.06626046]
8 [0.32155502 0.31111132]
9 [-0.02586914  0.06044301]
10 [0.29844191 0.29542878]
11 [0.06398512 0.06809256]
12 [0.02662425 0.03430103]
13 [0.04855366 0.04281284]


In [54]:
np.array(B)@np.array(W[0])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [7]:
0.5 * Jc1 + 0.5 * m * (a1)**2 + m * a1 * r2 * cos(beta[i]) + 0.5 * m * (r2)**2 + 0.5 * Jc2

TypeError: can't multiply sequence by non-int of type 'float'

In [32]:
 np.transpose(E[0])

array([0.04914857, 0.02066625])

In [36]:
np.eye(2)@E[0]

array([0.04914857, 0.02066625])

In [61]:
np.array(B).reshape(2,-1)

array([[-0.03716038, -0.01858019],
       [ 0.00817272,  0.        ]])